### ISSUE TITLE
Cerebral TodoMVC with a Morepath REST backend

### ISSUE THREAD

**Issue by henri-hulski** [morepath/morepath_reactredux#1]
I just uploaded [morepath_cerebral_todomvc](https://github.com/henri-hulski/morepath_cerebral_todomvc), a Cerebral TodoMVC with a Morepath REST backend.

Cerebral is a controller layer original for React and Baobab. But now you can use it also with other view and model layers.
It works with signals, which triggers actions. I like this workflow.
Cerebral has also a very nice debugger for Chrome which allows you to observe your signals and state changes. Time travelling and state saving refresh is also possible.

@faassen: If you want we can transfer this Repo to the morepath organization.

**Comment by faassen** [comment]
Cool, yes, I think you need to initiate the transfer, please do!

**Comment by henri-hulski** [comment]
Actually I need Admin rights to initiate the transfer ;-)

**Comment by faassen** [comment]
Oh, yeah, I ran into that one before. I'll give you admin rights.

**Comment by faassen** [comment]
Okay, I gave you admin rights. Go ahead and transfer!

**Comment by henri-hulski** [comment]
Done!

**Comment by faassen** [comment]
Thank you!
